[package]
name = "raj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["cargo"] }
log = "0.4"
env_logger = "0.9.0"

[dev-dependencies]
serial_test = "*"